### ISSUE TITLE
DOMException: GATT Error Unknown.

### ISSUE THREAD

**Issue by teevik** [thegecko/microbit-web-bluetooth#7]
Hey, i was trying out the demo at https://thegecko.github.io/microbit-web-bluetooth/examples/index.html , but i'm getting a `DOMException: GATT Error Unknown.` error: ![Lu4X1Ov](https://user-images.githubusercontent.com/9365365/71325190-7f4db380-24e9-11ea-896c-ec625ff34ef8.png)

It connects to the microbit, but errors when doing `getServices(device)`. So on the leds it does a flash of the `✔` and then goes back to an `X`

I'm using the `no-magnet-no-io` hex from https://github.com/thegecko/microbit-web-bluetooth/blob/master/hex/ble-open-no-magnet-no-io.hex on the microbit, is there anything else i need to do for it to work?

**Comment by thegecko** [comment]
Which browser/OS?

**Comment by teevik** [comment]
Windows 10, i tried both chrome and chrome canary

**Comment by thegecko** [comment]
Hi @teevik 

Unfortunately I don't have access to a Windows machine with bluetooth.

I tried [ble-open-no-magnet-no-io.hex](https://github.com/thegecko/microbit-web-bluetooth/blob/master/hex/ble-open-no-magnet-no-io.hex) on the latest Chrome (version 79.xx) for MacOS and Android and the examples work fine.

I tried the [web-bluetooth example](https://thegecko.github.io/microbit-web-bluetooth/examples/index.html) and the [web components example](https://thegecko.github.io/microbit-web-components/examples/index.html)

As these work, I don't think the issue is with the firmware. Can you try it on a different machine?

Has anyone else seen this issue?

**Comment by teevik** [comment]
Alright, I can try it on my desktop after holidays, you can close the issue for now if you want

Thanks for the help 😀
